name: CI-CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Print Java version
        run: java -version

      - name: Print Maven version
        run: mvn -version

      - name: Set up environment variables
        run: echo "TOKEN=${{ secrets.TOKEN }}" >> $GITHUB_ENV

      - name: Build with Maven
        run: mvn clean install

      - name: Run tests
        run: mvn test

      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: target/surefire-reports/

      - name: Archive logs
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: build-logs
          path: target/*.log